version: "3.9"
services:
  redis:
    image: "redis:5.0.6"
    container_name: my-test-redis
    ports:
     - "29179:6379"
  postgres:
    image: "postgres:12.7"
    container_name: my-test-postgres
    ports:
     - "29132:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: devuser
      POSTGRES_DB: devdb




